#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update
sudo apt-get  install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
# testing Nginx configuration
sudo nginx -t
sudo service nginx reload